### ISSUE TITLE
Missing the py file for preprocessing the data

### ISSUE THREAD

**Issue by albertcust** [BeileiCui/MSS-TFAL#2]
Thanks for the implementation. I am following this work. 

In the summary.txt saying:
# 1. You first need to convert the RGB label to class-level label with:
python generate_noise/to_class_label.py

However, no such py file in this folder.

**Comment by BeileiCui** [comment]
@albertcust Thanks for your comments. I forgot to upload the file before. I have uploaded it just now.

**Comment by albertcust** [comment]
Thanks for the active response!
